# Generated by Django 4.1.4 on 2022-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название книги')),
                ('author', models.CharField(max_length=150, verbose_name='Автор книги')),
                ('code', models.IntegerField(verbose_name='Персональный код книги')),
                ('in_library', models.BooleanField(verbose_name='Наличие книги')),
            ],
        ),
    ]
